### ISSUE TITLE
crabtyper.com leads to 404

### ISSUE THREAD

**Issue by Xithrius** [brancobruyneel/crabtyper#19]
[crabtyper.com](https://www.crabtyper.com) seems to be unusable. Will it be revived? I enjoyed this site quite a lot.

<img width="615" alt="image" src="https://user-images.githubusercontent.com/15021300/209484684-8f630e52-cc18-45aa-9e94-bdfaaf168a09.png">

**Comment by brancobruyneel** [comment]
I will revive it this week, been busy with work :) My apologies for letting it so long down, it was hosted on my student account.

**Comment by Xithrius** [comment]
I see. Thanks for the quick update. ❤️ 

Happy holidays!

**Comment by brancobruyneel** [comment]
Happy holidays :)
