### ISSUE TITLE
International Keyboard causes issues

### ISSUE THREAD

**Issue by domhel** [brancobruyneel/crabtyper#5]
Try using an international keyboard layout and when you approach "" it's randomly not working. Text shows red even though " was entered. Maybe there is a second " but it is not showing at least. And if the text after the closing " is red and you want to type (, it won't let you.

**Comment by brancobruyneel** [comment]
Weird, do you know which code snippet it was? Or does the problem occur on every snippet?

**Comment by domhel** [comment]
Sorry. I tried it but forgot to answer. I could not replicate the error, as far as I know. So you can keep it closed.
