### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by tawaliou** [brancobruyneel/crabtyper#7]
Hi @brancobruyneel I hope you're doing well. 
I'm junior web developer (JS/TS/React) and I'm currently learning Rust too. I want to contribute to your project to learn more Rust, Yew and help with features and issues...

**Comment by brancobruyneel** [comment]
Hi! Great, you are at the early stages of the project ;) I'll try to add more issues related to Yew, so that you can pick one that interests you.

**Comment by tawaliou** [comment]
OK cool.

**Comment by tawaliou** [comment]
@brancobruyneel have an idea of how I can run on my local machines the project ?
`cargo install` but got error like this : 
`error: found a virtual manifest at `C:\Users\Tawaliou.A\Documents\Rust\OSS\crabtyper\Cargo.toml` instead of a package manifest`

**Comment by brancobruyneel** [comment]
You don't need to run `cargo install`. For the api you can just `cd` into `crates/api` and execute `cargo run`.

As for the web, if you have node installed, you can `cd` into `crates/web` and run `npm setup`. This should add the `wasm-32-unkown-unkown` target to your rustup toolchain (required to be able to compile to wasm) and install trunk. Then you can run `npm install` and `API_URL=/api/snippets/random npm run dev`.
